[tool.poetry]
name = "name"
version = "0.1.0"
description = "Add description here"
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{ include = "name" }]

[tool.poetry.dependencies]
python = "^3.12"

[tool.poetry.scripts]
name = "name.__main__:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 100
target-version = "py312"

[tool.pyright]
typeCheckingMode = "basic"
