{ config, lib, ... }:
{
    options.biryani.programs.browsers = {
        enable = lib.mkOption {
            type = lib.types.bool;
            description = "Enable browser configuration through Home Manager.";
        };

        brave = {
            enable = lib.mkOption {
                type = lib.types.bool;
                description = "Enable Brave through Home Manager.";
            };

            cmd_args = lib.mkOption {
                type = lib.types.listOf lib.types.str;
                description = "Command-line arguments passed to Brave.";
            };
        };
    };

    config =
        let
            biryani_browsers = config.biryani.programs.browsers;
            biryani_theming = config.biryani.theming;
            palette =
                if biryani_theming.matugen.integrations.brave.enable then
                    biryani_theming.palette.matugen
                else
                    biryani_theming.palette.static;
            hexByte = value: (builtins.fromTOML "x = 0x${value}").x;
            rgbArg =
                color:
                let
                    hex = lib.removePrefix "#" color;
                    r = hexByte (builtins.substring 0 2 hex);
                    g = hexByte (builtins.substring 2 2 hex);
                    b = hexByte (builtins.substring 4 2 hex);
                in
                "${toString r},${toString g},${toString b}";
            themeArgs = lib.optionals biryani_theming.matugen.integrations.brave.enable [
                "--install-autogenerated-theme=${rgbArg palette.primary}"
            ];
        in
        lib.mkIf (biryani_browsers.enable && biryani_browsers.brave.enable) {
            programs.brave = {
                enable = true;
                commandLineArgs = biryani_browsers.brave.cmd_args ++ themeArgs;
            };
        };
}
