{ config, lib, ... }: {
    options.biryani.programs.browsers.chrome = {
        enable = lib.mkOption {
            type = lib.types.bool;
            description = "Enable Google Chrome through Home Manager.";
        };

        cmd_args = lib.mkOption {
            type = lib.types.listOf lib.types.str;
            description = "Command-line arguments passed to Google Chrome.";
        };

        extensions = lib.mkOption {
            type = lib.types.anything;
            description = "Google Chrome extension configuration passed through for future browser modules.";
        };
    };

    config =
        let
            biryani_browsers = config.biryani.programs.browsers;
            biryani_theming = config.biryani.theming;
            palette =
                if biryani_theming.matugen.integrations.chrome.enable then
                    biryani_theming.palette.matugen
                else
                    biryani_theming.palette.static;
            hexByte = value: (builtins.fromTOML "x = 0x${value}").x;
            rgbArg =
                color:
                let
                    hex = lib.removePrefix "#" color;
                    r = hexByte (builtins.substring 0 2 hex);
                    g = hexByte (builtins.substring 2 2 hex);
                    b = hexByte (builtins.substring 4 2 hex);
                in
                "${toString r},${toString g},${toString b}";
            themeArgs = lib.optionals biryani_theming.matugen.integrations.chrome.enable [
                "--install-autogenerated-theme=${rgbArg palette.primary}"
            ];
        in
        lib.mkIf (biryani_browsers.enable && biryani_browsers.chrome.enable) {
            programs.google-chrome = {
                enable = true;
                commandLineArgs = biryani_browsers.chrome.cmd_args ++ themeArgs;
            };
        };
}
